# permissions for end users to edit encrypteddomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: encrypteddomain-editor-role
rules:
- apiGroups:
  - letsencrypt.operatingopenshift.org
  resources:
  - encrypteddomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - letsencrypt.operatingopenshift.org
  resources:
  - encrypteddomains/status
  verbs:
  - get
