
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - letsencrypt.operatingopenshift.org
  resources:
  - encrypteddomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - letsencrypt.operatingopenshift.org
  resources:
  - encrypteddomains/finalizers
  verbs:
  - update
- apiGroups:
  - letsencrypt.operatingopenshift.org
  resources:
  - encrypteddomains/status
  verbs:
  - get
  - patch
  - update
