//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Manuel Dewald.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptedDomain) DeepCopyInto(out *EncryptedDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptedDomain.
func (in *EncryptedDomain) DeepCopy() *EncryptedDomain {
	if in == nil {
		return nil
	}
	out := new(EncryptedDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EncryptedDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptedDomainList) DeepCopyInto(out *EncryptedDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EncryptedDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptedDomainList.
func (in *EncryptedDomainList) DeepCopy() *EncryptedDomainList {
	if in == nil {
		return nil
	}
	out := new(EncryptedDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EncryptedDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptedDomainSpec) DeepCopyInto(out *EncryptedDomainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptedDomainSpec.
func (in *EncryptedDomainSpec) DeepCopy() *EncryptedDomainSpec {
	if in == nil {
		return nil
	}
	out := new(EncryptedDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EncryptedDomainStatus) DeepCopyInto(out *EncryptedDomainStatus) {
	*out = *in
	if in.GeneratedCertificates != nil {
		in, out := &in.GeneratedCertificates, &out.GeneratedCertificates
		*out = make(map[string]GeneratedCertificate, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EncryptedDomainStatus.
func (in *EncryptedDomainStatus) DeepCopy() *EncryptedDomainStatus {
	if in == nil {
		return nil
	}
	out := new(EncryptedDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GeneratedCertificate) DeepCopyInto(out *GeneratedCertificate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GeneratedCertificate.
func (in *GeneratedCertificate) DeepCopy() *GeneratedCertificate {
	if in == nil {
		return nil
	}
	out := new(GeneratedCertificate)
	in.DeepCopyInto(out)
	return out
}
